DROP TABLE CONDITION;

CREATE TABLE CONDITION(
    CONDITIONNO    NUMBER(10)       NOT NULL PRIMARY KEY,
    TITLE          VARCHAR2(100)    NOT NULL UNIQUE, 
    CONTENT        CLOB             NOT NULL, 
    MINPRICE       NUMBER(10)       NOT NULL, 
    MAXPRICE       NUMBER(10)       NOT NULL,   
    CHILDREN       NUMBER(10)       NOT NULL
);

COMMENT ON TABLE CONDITION is '조건';
COMMENT ON COLUMN CONDITION.CONDITIONNO is '조건 번호';
COMMENT ON COLUMN CONDITION.TITLE is '조건 제목';
COMMENT ON COLUMN CONDITION.CONTENT is '조건 내용';
COMMENT ON COLUMN CONDITION.MINPRICE is '최소 가격';
COMMENT ON COLUMN CONDITION.MAXPRICE is '최대 가격';
COMMENT ON COLUMN CONDITION.CHILDREN is '자녀수';

DROP SEQUENCE condition_seq;
CREATE SEQUENCE condition_seq
  START WITH 1              -- 시작 번호
  INCREMENT BY 1          -- 증가값
  MAXVALUE 9999999999 -- 최대값: 9999999 --> NUMBER(7) 대응
  CACHE 2                       -- 2번은 메모리에서만 계산
  NOCYCLE;                     -- 다시 1부터 생성되는 것을 방지