DROP TABLE WISHLIST;

CREATE TABLE WISHLIST(
    WISHLISTNO          NUMBER(10)       NOT NULL PRIMARY KEY,
    CUSTOMERNO          NUMBER(10)       NOT NULL, 
    CARNO               NUMBER(10)       NOT NULL,
    REVIEWNO            NUMBER(10)       NOT NULL,
    WISHLISTPRICE       NUMBER(10)       NOT NULL,
    FOREIGN KEY (CUSTOMERNO) REFERENCES CUSTOMER (CUSTOMERNO),
    FOREIGN KEY (CARNO) REFERENCES CAR (CARNO),
    FOREIGN KEY (REVIEWNO) REFERENCES REVIEW (REVIEWNO)
);

COMMENT ON TABLE WISHLIST is '관심 차량';
COMMENT ON COLUMN WISHLIST.WISHLISTNO is '관심 차량 번호';
COMMENT ON COLUMN WISHLIST.CUSTOMERNO is '고객 번호';
COMMENT ON COLUMN WISHLIST.CARNO is '자동차 번호';
COMMENT ON COLUMN WISHLIST.REVIEWNO is '후기 번호';
COMMENT ON COLUMN WISHLIST.WISHLISTPRICE is '관심 차량 가격';

DROP SEQUENCE wishlist_seq;
CREATE SEQUENCE wishlist_seq
  START WITH 1              -- 시작 번호
  INCREMENT BY 1          -- 증가값
  MAXVALUE 9999999999 -- 최대값: 9999999 --> NUMBER(7) 대응
  CACHE 2                       -- 2번은 메모리에서만 계산
  NOCYCLE;                     -- 다시 1부터 생성되는 것을 방지